### ISSUE TITLE
Hi asimlqt , pls tell me how can correct the error Fatal error: Uncaught exception 'Exception' with message 'String could not be parsed as XML' in D:\www\htdocs\ok\ss\vendor\asimlqt\php-google-spreadsheet-client\src\Google\Spreadsheet\SpreadsheetFeed.php:45 Stack trace: #0 D:\www\htdocs\ok\ss\vendor\asimlqt\php-google-spreadsheet-client\src\Google\Spreadsheet\SpreadsheetFeed.php(45): SimpleXMLElement->__construct('') #1 D:\www\htdocs\ok\ss\vendor\asimlqt\php-google-spreadsheet-client\src\Google\Spreadsheet\SpreadsheetService.php(39): Google\Spreadsheet\SpreadsheetFeed->__construct(false) #2 D:\www\htdocs\ok\ss\aa.php(46): Google\Spreadsheet\SpreadsheetService->getSpreadsheets() #3 {main} thrown in D:\www\htdocs\ok\ss\vendor\asimlqt\php-google-spreadsheet-client\src\Google\Spreadsheet\SpreadsheetFeed.php on line 45

### ISSUE THREAD

**Issue by hokage4** [asimlqt/php-google-spreadsheet-client#123]

**Comment by asimlqt** [comment]
You haven't set a valid oauth token.
