### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by av2222** [asimlqt/php-google-spreadsheet-client#164]
$spreadsheetService = new Google\Spreadsheet\SpreadsheetService();
$spreadsheetFeed = $spreadsheetService->getSpreadsheetFeed();
$spreadsheet = $spreadsheetFeed->getByTitle('test');

Fatal error: Uncaught exception 'Google\Spreadsheet\Exception\SpreadsheetNotFoundException' in C:\OpenServer\domains\GoogleDocs\vendor\asimlqt\php-google-spreadsheet-client\src\Google\Spreadsheet\SpreadsheetFeed.php:100 Stack trace: #0 C:\OpenServer\domains\GoogleDocs\index.php(39): Google\Spreadsheet\SpreadsheetFeed->getByTitle('test') #1 {main} thrown in C:\OpenServer\domains\GoogleDocs\vendor\asimlqt\php-google-spreadsheet-client\src\Google\Spreadsheet\SpreadsheetFeed.php on line 100

**Comment by arafatsky99** [comment]
you need share 'test' Spreadsheet file to email something like  @graphite-willow-146111.iam.gserviceaccount.com

**Comment by rachitharoun** [comment]
Thanks thanks arafatsky99

**Comment by kirti275** [comment]
![image](https://user-images.githubusercontent.com/17165482/30733817-3c166100-9f96-11e7-881b-f632ce48dcad.png)

**Comment by legreco** [comment]
thanks! very helpful

**Comment by brack11** [comment]
I've got simular  issue but with reading public spreadsheet code looks like:
`use Google\Spreadsheet\DefaultServiceRequest;
use Google\Spreadsheet\ServiceRequestFactory;

$serviceRequest = new DefaultServiceRequest("");
ServiceRequestFactory::setInstance($serviceRequest);

$spreadsheetService = new Google\Spreadsheet\SpreadsheetService();
$worksheetFeed = $spreadsheetService->getPublicSpreadsheet("1zKMY66aaev3htO5015cHp8wwxKC3J4roEGbXOKC077M");
`
and respond with 
`PHP Fatal error:  Uncaught Google\Spreadsheet\Exception\ResourceNotFoundException: Internal Error in /home2/swarlorg/public_html/bodybuilders/swarl_cert/vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/SpreadsheetService.php:76
Stack trace:
#0 /vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/SpreadsheetService.php(98): Google\Spreadsheet\SpreadsheetService->getResourceById('Google\\Spreadsh...', 'https://spreads...')
#1 /certificate.php(14): Google\Spreadsheet\SpreadsheetService->getPublicSpreadsheet('1zKMY66aaev3htO...')
#2 {main}
  thrown in /vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/SpreadsheetService.php on line 76`
Two days ago everything was working, the only change was addition of around 200 records to the spreadsheet. Please help!
