### ISSUE TITLE
ResourceNotFoundException thrown

### ISSUE THREAD

**Issue by brack11** [asimlqt/php-google-spreadsheet-client#197]
Two days ago my script that used your code stopped working, throwing ResourceNotFoundException on line 76 in /vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/SpreadsheetService.php My script contains lines:
<code>
use Google\Spreadsheet\DefaultServiceRequest;
use Google\Spreadsheet\ServiceRequestFactory;

$serviceRequest = new DefaultServiceRequest("");
ServiceRequestFactory::setInstance($serviceRequest);

$spreadsheetService = new Google\Spreadsheet\SpreadsheetService();
$worksheetFeed = $spreadsheetService->getPublicSpreadsheet("1zKMY66aaev3htO5015cHp8wwxKC3J4roEGbXOKC077M");
</code>
Error looks like this:
<code>
PHP Fatal error:  Uncaught Google\Spreadsheet\Exception\ResourceNotFoundException: Internal Error in /home2/swarlorg/public_html/bodybuilders/swarl_cert/vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/SpreadsheetService.php:76
Stack trace:
#0 /.../vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/SpreadsheetService.php(98): Google\Spreadsheet\SpreadsheetService->getResourceById('Google\\Spreadsh...', 'https://spreads...')
#1 /.../certificate.php(14): Google\Spreadsheet\SpreadsheetService->getPublicSpreadsheet('1zKMY66aaev3htO...')
#2 {main}
  thrown in /.../vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/SpreadsheetService.php on line 76
</code>
What could it be? issue in my code? my provider? or google changed API?
Spreadsheet is public for view for everyone

**Comment by PYDeret** [comment]
I've got the same error, do you have any fix to this ?
